# This is a basic workflow to help you get started with Actions

name: Deploy do SITE-MP para o AWS EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  copy-site-por-ssh:
    environment: Development
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run SSH Comand with Secrets
        run: 
          echo "${{secret.SSH_PIVATE_KEY}}" > chave_site.pem
          chmod 400 chave_site.pem
          scp -o StrictHostKeyChecking=no -i site_chave.pem *.css *.html ubuntu@ec2-18-156-78-72.eu-central-1.compute.amazonaws.com:/var/www/html/mp/

